### ISSUE TITLE
Create common build configuration

### ISSUE THREAD

**Issue by DomHoney** [logdyn/keeper#19]
Right now there is nothing in the repo to allow someone to create a runnable jar.

Maven should be configured to reliably produce a runnable jar (either executable or with `java -jar`).
i.e. `mvn package` and/or `mvn install` should do something useful.

(Optionally) create and commit IntelliJ Build/Run/Debug configurations

**Comment by jsjlewis96** [comment]
Also looking into POM versioning like you said

**Comment by DomHoney** [comment]
Resolved by #20
